version: "3.8"
services:
  frontend:
    image: ate-frontend-dev
    container_name: ate-frontend-dev
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./frontend/container/aofe-frontend:/usr/frontend/src/app
    networks:
      ate-network: {}
    ports:
      - "8050:4200"