version: "3.8"
services:
  frontend:
    image: ate-frontend-dev
    container_name: ate-frontend-dev
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/container/aofe-frontend:/usr/frontend/src/app
    networks:
      ate-network: {}
    ports:
      - "8050:4200"

  backend:
    image: ate-backend-dev
    container_name: ate-backend-dev
    build:
      context: ./backend
    volumes:
      - ./backend/container/aofe-backend:/usr/backend/src/app
    networks:
      ate-network: {}
    restart: on-failure