version: "3.8"
services:
  frontend:
    image: ate-frontend-dev
    container_name: ate-frontend-dev
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/container/aofe-frontend:/app
    networks:
      ate-network: {}
    ports:
      - "8050:4200"

  backend:
    command: npm run dev
    image: ate-backend-dev
    container_name: ate-backend-dev
    build:
      context: ./backend
    volumes:
      - ./backend/container/aofe-backend:/app
    networks:
      ate-network: {}
    restart: on-failure

  database:
    container_name: ate-database-dev
    volumes:
      - /ate-dev/db:/data/db
    ports:
      - "8051:27017"