version: "3.7"
services:
  backend:
    image: ate-backend
    container_name: ate-backend
    command: npm run start
    depends_on:
      - database
    environment:
      ADMIN_USER_USERNAME : ${ADMIN_USER_USERNAME}
      ADMIN_USER_PASSWORD : ${ADMIN_USER_PASSWORD}
      DATABASE_USER_USERNAME : ${DATABASE_USER_USERNAME}
      DATABASE_USER_PASSWORD : ${DATABASE_USER_PASSWORD}
      SESSION_SECRET : ${SESSION_SECRET}
    ports:
      - "90:80"
    build:
      context: ./backend
      dockerfile: prod.Dockerfile
    networks:
      ate-network: {}
    restart: on-failure

  database:
    command: mongod --quiet --logpath /dev/null
    image: mongo
    container_name: ate-database
    environment:
       MONGO_INITDB_ROOT_USERNAME : ${DATABASE_USER_USERNAME}
       MONGO_INITDB_ROOT_PASSWORD : ${DATABASE_USER_PASSWORD}
       MONGO_INITDB_DATABASE : Arena
    networks:
      ate-network:
        aliases:
          - mongo
          - db
    restart: on-failure


networks:
  ate-network:
