version: "3.7"
services:
  # COMMON SERVICES
  reverse-proxy:
    image: ate-reverse-proxy
    container_name: ate-reverse-proxy
    build:
      context: ./reverse_proxy
      dockerfile: Dockerfile
    networks:
      ate-network: {}
    depends_on:
      - frontend
      - backend
      # - database
    ports:
      - "80:80"
      - "443:443"
    restart: on-failure

  frontend:
    image: ate-frontend
    container_name: ate-frontend
    build:
      context: ./frontend
      dockerfile: prod.Dockerfile
    networks:
      ate-network: {}
    restart: on-failure

  backend:
    image: ate-backend
    container_name: ate-backend
    command: npm run start
    build:
      context: ./backend
      dockerfile: prod.Dockerfile
    networks:
      ate-network: {}
    restart: on-failure

networks:
  ate-network:
