version: "3.7"
services:
  reverse-proxy:
    image: ate-reverse-proxy
    container_name: ate-reverse-proxy
    build:
      context: ./reverse_proxy
      dockerfile: Dockerfile
    networks:
      ate-network: {}
    depends_on:
      - frontend
      - backend
      - database
    ports:
      - "80:80"
      - "443:443"
    restart: on-failure

  frontend:
    image: ate-frontend
    container_name: ate-frontend
    build:
      context: ./frontend
      dockerfile: prod.Dockerfile
    networks:
      ate-network: {}
    restart: on-failure

  backend:
    image: ate-backend
    container_name: ate-backend
    command: npm run start
    depends_on:
      - database
    environment:
      ADMIN_USER_USERNAME : ${ADMIN_USER_USERNAME}
      ADMIN_USER_PASSWORD : ${ADMIN_USER_PASSWORD}
      DATABASE_USER_USERNAME : ${DATABASE_USER_USERNAME}
      DATABASE_USER_PASSWORD : ${DATABASE_USER_PASSWORD}
    build:
      context: ./backend
      dockerfile: prod.Dockerfile
    networks:
      ate-network: {}
    restart: on-failure

  database:
    command: mongod --quiet --logpath /dev/null
    image: mongo
    container_name: ate-database
    environment:
       MONGO_INITDB_ROOT_USERNAME : ${DATABASE_USER_USERNAME}
       MONGO_INITDB_ROOT_PASSWORD : ${DATABASE_USER_PASSWORD}
       MONGO_INITDB_DATABASE : Arena
    networks:
      ate-network:
        aliases:
          - mongo
          - db
    volumes:
      - /ate/db:/data/db
    restart: on-failure


networks:
  ate-network:
